# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from client.models.v1_resource_quota import V1ResourceQuota

class TestV1ResourceQuota(unittest.TestCase):
    """V1ResourceQuota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ResourceQuota:
        """Test V1ResourceQuota
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ResourceQuota`
        """
        model = V1ResourceQuota()
        if include_optional:
            return V1ResourceQuota(
                api_version = '',
                kind = '',
                metadata = client.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                            api_version = '', 
                            fields_type = '', 
                            fields_v1 = client.models.fields_v1.fieldsV1(), 
                            manager = '', 
                            operation = '', 
                            subresource = '', 
                            time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        client.models.v1/owner_reference.v1.OwnerReference(
                            api_version = '', 
                            block_owner_deletion = True, 
                            controller = True, 
                            kind = '', 
                            name = '', 
                            uid = '', )
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = client.models.v1/resource_quota_spec.v1.ResourceQuotaSpec(
                    hard = {
                        'key' : ''
                        }, 
                    scope_selector = client.models.v1/scope_selector.v1.ScopeSelector(
                        match_expressions = [
                            client.models.v1/scoped_resource_selector_requirement.v1.ScopedResourceSelectorRequirement(
                                operator = '', 
                                scope_name = '', 
                                values = [
                                    ''
                                    ], )
                            ], ), 
                    scopes = [
                        ''
                        ], ),
                status = client.models.v1/resource_quota_status.v1.ResourceQuotaStatus(
                    hard = {
                        'key' : ''
                        }, 
                    used = {
                        'key' : ''
                        }, )
            )
        else:
            return V1ResourceQuota(
        )
        """

    def testV1ResourceQuota(self):
        """Test V1ResourceQuota"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
