# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from client.models.v1beta2_flow_schema import V1beta2FlowSchema

class TestV1beta2FlowSchema(unittest.TestCase):
    """V1beta2FlowSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2FlowSchema:
        """Test V1beta2FlowSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2FlowSchema`
        """
        model = V1beta2FlowSchema()
        if include_optional:
            return V1beta2FlowSchema(
                api_version = '',
                kind = '',
                metadata = client.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                            api_version = '', 
                            fields_type = '', 
                            fields_v1 = client.models.fields_v1.fieldsV1(), 
                            manager = '', 
                            operation = '', 
                            subresource = '', 
                            time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        client.models.v1/owner_reference.v1.OwnerReference(
                            api_version = '', 
                            block_owner_deletion = True, 
                            controller = True, 
                            kind = '', 
                            name = '', 
                            uid = '', )
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = client.models.v1beta2/flow_schema_spec.v1beta2.FlowSchemaSpec(
                    distinguisher_method = client.models.v1beta2/flow_distinguisher_method.v1beta2.FlowDistinguisherMethod(
                        type = '', ), 
                    matching_precedence = 56, 
                    priority_level_configuration = client.models.v1beta2/priority_level_configuration_reference.v1beta2.PriorityLevelConfigurationReference(
                        name = '', ), 
                    rules = [
                        client.models.v1beta2/policy_rules_with_subjects.v1beta2.PolicyRulesWithSubjects(
                            non_resource_rules = [
                                client.models.v1beta2/non_resource_policy_rule.v1beta2.NonResourcePolicyRule(
                                    non_resource_urls = [
                                        ''
                                        ], 
                                    verbs = [
                                        ''
                                        ], )
                                ], 
                            resource_rules = [
                                client.models.v1beta2/resource_policy_rule.v1beta2.ResourcePolicyRule(
                                    api_groups = [
                                        ''
                                        ], 
                                    cluster_scope = True, 
                                    namespaces = [
                                        ''
                                        ], 
                                    resources = [
                                        ''
                                        ], 
                                    verbs = [
                                        ''
                                        ], )
                                ], 
                            subjects = [
                                client.models.v1beta2/subject.v1beta2.Subject(
                                    group = client.models.v1beta2/group_subject.v1beta2.GroupSubject(
                                        name = '', ), 
                                    kind = '', 
                                    service_account = client.models.v1beta2/service_account_subject.v1beta2.ServiceAccountSubject(
                                        name = '', 
                                        namespace = '', ), 
                                    user = client.models.v1beta2/user_subject.v1beta2.UserSubject(
                                        name = '', ), )
                                ], )
                        ], ),
                status = client.models.v1beta2/flow_schema_status.v1beta2.FlowSchemaStatus(
                    conditions = [
                        client.models.v1beta2/flow_schema_condition.v1beta2.FlowSchemaCondition(
                            last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            message = '', 
                            reason = '', 
                            status = '', 
                            type = '', )
                        ], )
            )
        else:
            return V1beta2FlowSchema(
        )
        """

    def testV1beta2FlowSchema(self):
        """Test V1beta2FlowSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
