# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from client.models.v2_pods_metric_status import V2PodsMetricStatus

class TestV2PodsMetricStatus(unittest.TestCase):
    """V2PodsMetricStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2PodsMetricStatus:
        """Test V2PodsMetricStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2PodsMetricStatus`
        """
        model = V2PodsMetricStatus()
        if include_optional:
            return V2PodsMetricStatus(
                current = client.models.v2/metric_value_status.v2.MetricValueStatus(
                    average_utilization = 56, 
                    average_value = '', 
                    value = '', ),
                metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                    name = '', 
                    selector = client.models.v1/label_selector.v1.LabelSelector(
                        match_expressions = [
                            client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                key = '', 
                                operator = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        match_labels = {
                            'key' : ''
                            }, ), )
            )
        else:
            return V2PodsMetricStatus(
                current = client.models.v2/metric_value_status.v2.MetricValueStatus(
                    average_utilization = 56, 
                    average_value = '', 
                    value = '', ),
                metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                    name = '', 
                    selector = client.models.v1/label_selector.v1.LabelSelector(
                        match_expressions = [
                            client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                key = '', 
                                operator = '', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        match_labels = {
                            'key' : ''
                            }, ), ),
        )
        """

    def testV2PodsMetricStatus(self):
        """Test V2PodsMetricStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
