# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from client.models.v2_horizontal_pod_autoscaler_list import V2HorizontalPodAutoscalerList

class TestV2HorizontalPodAutoscalerList(unittest.TestCase):
    """V2HorizontalPodAutoscalerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2HorizontalPodAutoscalerList:
        """Test V2HorizontalPodAutoscalerList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2HorizontalPodAutoscalerList`
        """
        model = V2HorizontalPodAutoscalerList()
        if include_optional:
            return V2HorizontalPodAutoscalerList(
                api_version = '',
                items = [
                    client.models.v2/horizontal_pod_autoscaler.v2.HorizontalPodAutoscaler(
                        api_version = '', 
                        kind = '', 
                        metadata = client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = client.models.v2/horizontal_pod_autoscaler_spec.v2.HorizontalPodAutoscalerSpec(
                            behavior = client.models.v2/horizontal_pod_autoscaler_behavior.v2.HorizontalPodAutoscalerBehavior(
                                scale_down = client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                                    policies = [
                                        client.models.v2/hpa_scaling_policy.v2.HPAScalingPolicy(
                                            period_seconds = 56, 
                                            type = '', 
                                            value = 56, )
                                        ], 
                                    select_policy = '', 
                                    stabilization_window_seconds = 56, ), 
                                scale_up = client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                                    select_policy = '', 
                                    stabilization_window_seconds = 56, ), ), 
                            max_replicas = 56, 
                            metrics = [
                                client.models.v2/metric_spec.v2.MetricSpec(
                                    container_resource = client.models.v2/container_resource_metric_source.v2.ContainerResourceMetricSource(
                                        container = '', 
                                        name = '', 
                                        target = client.models.v2/metric_target.v2.MetricTarget(
                                            average_utilization = 56, 
                                            average_value = '', 
                                            type = '', 
                                            value = '', ), ), 
                                    external = client.models.v2/external_metric_source.v2.ExternalMetricSource(
                                        metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                                            name = '', 
                                            selector = client.models.v1/label_selector.v1.LabelSelector(
                                                match_expressions = [
                                                    client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                                        key = '', 
                                                        operator = '', 
                                                        values = [
                                                            ''
                                                            ], )
                                                    ], 
                                                match_labels = {
                                                    'key' : ''
                                                    }, ), ), 
                                        target = client.models.v2/metric_target.v2.MetricTarget(
                                            average_utilization = 56, 
                                            average_value = '', 
                                            type = '', 
                                            value = '', ), ), 
                                    object = client.models.v2/object_metric_source.v2.ObjectMetricSource(
                                        described_object = client.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                                            api_version = '', 
                                            kind = '', 
                                            name = '', ), 
                                        metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                                            name = '', ), 
                                        target = , ), 
                                    pods = client.models.v2/pods_metric_source.v2.PodsMetricSource(
                                        metric = , 
                                        target = , ), 
                                    resource = client.models.v2/resource_metric_source.v2.ResourceMetricSource(
                                        name = '', 
                                        target = , ), 
                                    type = '', )
                                ], 
                            min_replicas = 56, 
                            scale_target_ref = client.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                                api_version = '', 
                                kind = '', 
                                name = '', ), ), 
                        status = client.models.v2/horizontal_pod_autoscaler_status.v2.HorizontalPodAutoscalerStatus(
                            conditions = [
                                client.models.v2/horizontal_pod_autoscaler_condition.v2.HorizontalPodAutoscalerCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '', 
                                    reason = '', 
                                    status = '', 
                                    type = '', )
                                ], 
                            current_metrics = [
                                client.models.v2/metric_status.v2.MetricStatus(
                                    type = '', )
                                ], 
                            current_replicas = 56, 
                            desired_replicas = 56, 
                            last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            observed_generation = 56, ), )
                    ],
                kind = '',
                metadata = client.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else:
            return V2HorizontalPodAutoscalerList(
                items = [
                    client.models.v2/horizontal_pod_autoscaler.v2.HorizontalPodAutoscaler(
                        api_version = '', 
                        kind = '', 
                        metadata = client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = client.models.v2/horizontal_pod_autoscaler_spec.v2.HorizontalPodAutoscalerSpec(
                            behavior = client.models.v2/horizontal_pod_autoscaler_behavior.v2.HorizontalPodAutoscalerBehavior(
                                scale_down = client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                                    policies = [
                                        client.models.v2/hpa_scaling_policy.v2.HPAScalingPolicy(
                                            period_seconds = 56, 
                                            type = '', 
                                            value = 56, )
                                        ], 
                                    select_policy = '', 
                                    stabilization_window_seconds = 56, ), 
                                scale_up = client.models.v2/hpa_scaling_rules.v2.HPAScalingRules(
                                    select_policy = '', 
                                    stabilization_window_seconds = 56, ), ), 
                            max_replicas = 56, 
                            metrics = [
                                client.models.v2/metric_spec.v2.MetricSpec(
                                    container_resource = client.models.v2/container_resource_metric_source.v2.ContainerResourceMetricSource(
                                        container = '', 
                                        name = '', 
                                        target = client.models.v2/metric_target.v2.MetricTarget(
                                            average_utilization = 56, 
                                            average_value = '', 
                                            type = '', 
                                            value = '', ), ), 
                                    external = client.models.v2/external_metric_source.v2.ExternalMetricSource(
                                        metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                                            name = '', 
                                            selector = client.models.v1/label_selector.v1.LabelSelector(
                                                match_expressions = [
                                                    client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                                        key = '', 
                                                        operator = '', 
                                                        values = [
                                                            ''
                                                            ], )
                                                    ], 
                                                match_labels = {
                                                    'key' : ''
                                                    }, ), ), 
                                        target = client.models.v2/metric_target.v2.MetricTarget(
                                            average_utilization = 56, 
                                            average_value = '', 
                                            type = '', 
                                            value = '', ), ), 
                                    object = client.models.v2/object_metric_source.v2.ObjectMetricSource(
                                        described_object = client.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                                            api_version = '', 
                                            kind = '', 
                                            name = '', ), 
                                        metric = client.models.v2/metric_identifier.v2.MetricIdentifier(
                                            name = '', ), 
                                        target = , ), 
                                    pods = client.models.v2/pods_metric_source.v2.PodsMetricSource(
                                        metric = , 
                                        target = , ), 
                                    resource = client.models.v2/resource_metric_source.v2.ResourceMetricSource(
                                        name = '', 
                                        target = , ), 
                                    type = '', )
                                ], 
                            min_replicas = 56, 
                            scale_target_ref = client.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                                api_version = '', 
                                kind = '', 
                                name = '', ), ), 
                        status = client.models.v2/horizontal_pod_autoscaler_status.v2.HorizontalPodAutoscalerStatus(
                            conditions = [
                                client.models.v2/horizontal_pod_autoscaler_condition.v2.HorizontalPodAutoscalerCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '', 
                                    reason = '', 
                                    status = '', 
                                    type = '', )
                                ], 
                            current_metrics = [
                                client.models.v2/metric_status.v2.MetricStatus(
                                    type = '', )
                                ], 
                            current_replicas = 56, 
                            desired_replicas = 56, 
                            last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            observed_generation = 56, ), )
                    ],
        )
        """

    def testV2HorizontalPodAutoscalerList(self):
        """Test V2HorizontalPodAutoscalerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
