# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from client.models.v1_session_affinity_config import V1SessionAffinityConfig

class TestV1SessionAffinityConfig(unittest.TestCase):
    """V1SessionAffinityConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionAffinityConfig:
        """Test V1SessionAffinityConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionAffinityConfig`
        """
        model = V1SessionAffinityConfig()
        if include_optional:
            return V1SessionAffinityConfig(
                client_ip = client.models.v1/client_ip_config.v1.ClientIPConfig(
                    timeout_seconds = 56, )
            )
        else:
            return V1SessionAffinityConfig(
        )
        """

    def testV1SessionAffinityConfig(self):
        """Test V1SessionAffinityConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
